name: qplot
description: A command-line utility for plotting piped data using Plotly JS.
version: 0.1.1
repository: https://github.com/thumbert/qplot

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  csv: ^6.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  qplot: qplot:main