name: qplot
description: A command-line utility for plotting piped data using Plotly JS.
version: 0.1.4
repository: https://github.com/thumbert/qplot

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  csv: ^7.1.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0

executables:
  qplot: qplot:main